---
# gitlab must use a docker image for dependencies
image: maven:3-jdk-8

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Building"
    - mvn compile

test-job:
  stage: test
  script:
    - echo "Testing"
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test jacoco:report
    - cat target/site/jacoco/index.html
  artifacts:
    paths:
      - target/surefire-reports/TEST-*.xml
      - target/site/jacoco/index.html
...