---
# gitlab must use a docker image for dependencies
image: rvancea/maven-chrome-jdk8:latest

variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

cache:
  paths:
    - .m2/repository
    - target

stages:
  - build
  - test
#  - visualize

build-job:
  stage: build
  script:
    - echo "Building"
    - mvn compile

test-job:
  stage: test
  script:
    - echo "Testing"
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test jacoco:report
#    - python jacoco_parser/parser.py target/site/jacoco/index.html
    - cat target/site/jacaco/index.html
#    - mvn clean
#    - mvn org.jacoco:jacoco-maven-plugin:prepare-agent install
#    - mvn test
#    - mvn jacoco:report
  artifacts:
    paths:
      - target/surefire-reports/TEST-*.xml
      - target/site/jacoco/index.html
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml

#visualize-coverage:
#  stage: visualize
#  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
#  script:
#    # convert report from jacoco to cobertura, using relative project path
#    - python /opt/cover2cover.py target/site/jacoco/jacoco.xml $CI_PROJECT_DIR/src/main/java/ > target/site/cobertura.xml
#  needs: ["test-job"]
#  artifacts:
#    reports:
#      cobertura: target/site/cobertura.xml