---
# gitlab must use a docker image for dependencies
image: rvancea/maven-chrome-jdk8:latest

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Building"
    - mvn compile
#    - mkdir build
#    - touch build/info.txt
#  artifacts:
#    paths:
#      - build/

test-job:
  stage: test
  script:
    - echo "Testing"
    - mvn clean test
#    - test -f "build/info.txt"