---
# gitlab must use a docker image for dependencies
image: rvancea/maven-chrome-jdk8:latest

variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

cache:
  paths:
    - .m2/repository
    - target

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Building"
    - mvn compile

test-job:
  stage: test
  script:
    - echo "Testing"
    - mvn test
    - condition: succeededOrFailed()
