---
stages:
  - build
  - test

build-job:
  stage: build
  script:
    - src/main/ui/Main.java
    - echo "Building"
#    - mkdir build
#    - touch build/info.txt
#  artifacts:
#    paths:
#      - build/

test-job:
  stage: test
  script:
    - echo "Testing"
#    - test -f "build/info.txt"